create table if not exists public.profiles (
  id uuid not null references auth.users on delete cascade,
  nome text,
  email text,
  created_at timestamp with time zone default now(),
  primary key (id)
);

alter table public.profiles enable row level security;

create policy "Users can view own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

create policy "Users can insert own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  tipo text not null check (tipo in ('income', 'expense')),
  descricao text not null,
  valor numeric(12,2) not null,
  categoria text not null,
  pessoa text,
  metodo text,
  cartao text,
  data date not null default current_date,
  observacoes text,
  created_at timestamp with time zone default now()
);

alter table public.transactions enable row level security;

create policy "Users can view own transactions"
on public.transactions
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own transactions"
on public.transactions
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update own transactions"
on public.transactions
for update
to authenticated
using (auth.uid() = user_id);

create policy "Users can delete own transactions"
on public.transactions
for delete
to authenticated
using (auth.uid() = user_id);

create table if not exists public.goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  titulo text not null,
  meta numeric(12,2) not null default 0,
  valor_guardado numeric(12,2) not null default 0,
  created_at timestamp with time zone default now()
);

alter table public.goals enable row level security;

create policy "Users can view own goals"
on public.goals
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own goals"
on public.goals
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update own goals"
on public.goals
for update
to authenticated
using (auth.uid() = user_id);

create policy "Users can delete own goals"
on public.goals
for delete
to authenticated
using (auth.uid() = user_id);
